files:
  annotations_file_csv: 'data\input\video\run1b_2018-05-29-14-02-47.ids_1.openpose.3d.csv'
  video_file: 'data\input\video\run1b_2018-05-29-14-02-47.ids_5.mp4'
  image_folder: 'data\input\frames'
  timestamps_file: 'data\input\video\run1b_2018-05-29-14-02-47.ids_5.timestamps'
  calibration_file: 'data\input\video\run1b_2018-05-29-14-02-47.ids_5.calibration.json'
  output_frames_folder: 'data\output\frames'
  output_video_folder: 'data\output\video'

smpl:
  smpl_model_path: 'human_body_models\smpl'

nlf:
  nlf_model_path: 'models\nlf_l_multi.torchscript'

video_processing:
  extract_frames: false
  image_start: 25000
  length: 10
  batch_size: 2

parallel:
  max_workers: 16
